const List = () => {
    return <div>List</div>;
};

export default List;

const data = [
    {
        id: 71,
        first_name: 'TEMP1',
        middle_name: null,
        last_name: 'Supervisor',
        role_id: 2,
        mcc: '+91',
        mobile: '6565656565',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'TEMP',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: 'irs',
        profile_picture: null,
        msi_user: null
    },
    {
        id: 70,
        first_name: 'Test 4 sup',
        middle_name: null,
        last_name: 'Test 4',
        role_id: 2,
        mcc: '+91',
        mobile: '6376437638',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'Test 4',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: 'irs',
        profile_picture: null,
        msi_user: null
    },
    {
        id: 68,
        first_name: 'Test2 Sup',
        middle_name: null,
        last_name: 'Test2',
        role_id: 2,
        mcc: '+91',
        mobile: '1234567654',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'Test2',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: 'irs',
        profile_picture: {
            id: 169,
            disk: 's3',
            filename: '3097ba99-64ff-4452-97af-ee4882a3d393',
            mime_type: 'image/jpeg',
            url: 'https://ntep-amc-dev.s3.ap-south-1.amazonaws.com/profile_picture/3097ba99-64ff-4452-97af-ee4882a3d393.jpg'
        },
        msi_user: null
    },
    {
        id: 67,
        first_name: 'Test Supervisor',
        middle_name: null,
        last_name: 'test',
        role_id: 2,
        mcc: '+91',
        mobile: '1234234122',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'test',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: 'irs',
        profile_picture: {
            id: 168,
            disk: 's3',
            filename: '91d9c82c-5336-4845-9e20-b4c8e29fa9b3',
            mime_type: 'image/jpeg',
            url: 'https://ntep-amc-dev.s3.ap-south-1.amazonaws.com/profile_picture/91d9c82c-5336-4845-9e20-b4c8e29fa9b3.jpg'
        },
        msi_user: null
    },
    {
        id: 65,
        first_name: 'Supervisor 02',
        middle_name: null,
        last_name: 'test',
        role_id: 2,
        mcc: '+91',
        mobile: '6060606060',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'ok',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    },
    {
        id: 63,
        first_name: 'supervisor01',
        middle_name: null,
        last_name: 'TEST',
        role_id: 2,
        mcc: '+91',
        mobile: '3030303030',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'ok',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: {
            id: 167,
            disk: 's3',
            filename: '5adad350-0d27-4e1b-980b-e5ab40322307',
            mime_type: 'image/jpeg',
            url: 'https://ntep-amc-dev.s3.ap-south-1.amazonaws.com/profile_picture/5adad350-0d27-4e1b-980b-e5ab40322307.jpeg'
        },
        msi_user: null
    },
    {
        id: 61,
        first_name: 'AMC',
        middle_name: null,
        last_name: 'Team Leader',
        role_id: 2,
        mcc: '+91',
        mobile: '8200240937',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'AMC',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    },
    {
        id: 58,
        first_name: 'TL',
        middle_name: null,
        last_name: 'User 4',
        role_id: 2,
        mcc: '+91',
        mobile: '9988776600',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'a',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    },
    {
        id: 55,
        first_name: 'TL',
        middle_name: null,
        last_name: 'User 3',
        role_id: 2,
        mcc: '+91',
        mobile: '8000080000',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'a',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    },
    {
        id: 50,
        first_name: 'TL',
        middle_name: null,
        last_name: 'User 2',
        role_id: 2,
        mcc: '+91',
        mobile: '8008008000',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'z',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    },
    {
        id: 49,
        first_name: 'TL',
        middle_name: null,
        last_name: 'User 1',
        role_id: 2,
        mcc: '+91',
        mobile: '8080808080',
        state_id: 1,
        city_id: 1,
        pincode: null,
        address: 'a',
        status: 'active',
        is_task_creation_allowed: false,
        is_force_logout: false,
        supervisor_type: null,
        profile_picture: null,
        msi_user: null
    }
];
